### ISSUE TITLE
Harden SandBank API

### ISSUE THREAD

**Issue by james-s-tayler** [nicostouch/sandbank#26]
- [x] secure API w/ JWT tokens
 - [ ] get rid of any default credentials (postgres, identity server)
 - [ ] ensure no authentication data is sent via HTTP GET methods
 - [ ] hash passwords securely + enforce password policy
 - [ ] ensure no sensitive data or PII is logged
 - [x] lock EF queries down to only data for the authenticated principal
